name       : haskell-transformers-base
version    : 0.4.4
release    : 1
source     :
    - http://hackage.haskell.org/package/transformers-base-0.4.4/transformers-base-0.4.4.tar.gz : 6aa3494fc70659342fbbb163035d5827ecfd8079e3c929e2372adf771fd52387
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a straightforward port of monadLib's BaseM typeclass to transformers.
description: |
    This package provides a straightforward port of monadLib's BaseM typeclass to transformers.
builddeps  :
    - haskell-cabal-install
    - haskell-stm
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
